# Keying Set: KeyingSet
import bpy

scene = bpy.context.scene

# Keying Set Level declarations
ks = scene.keying_sets.new(idname="KeyingSet", name="Lieutenant_Dan: All Controls")
ks.bl_description = "Key all controls fro Lieutenant Dan"

ks.bl_options = set()

# ID's that are commonly used
id_0 = bpy.data.objects["Lieutenant_Dan"]

# Path Definitions
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_ROOT"].location', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_ROOT"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_ROOT"].scale', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_ROOT"]["Show left leg"]', index=-1, group_method='NONE')
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_ROOT"]["Show right leg"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_ROOT"]["Show tail"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.L"].location', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.L"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.L"]["Auto Stretch"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.L"]["Foot Rock"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.L"]["Lengthen Calf"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.L"]["Lengthen Thigh"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.L"]["Twist At Ball"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.L"]["Twist At Heel"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.L"]["Twist At Toe"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Foot.L"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Toe.L"].rotation_euler', index=0)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Heel.L"].rotation_euler', index=0)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Toe.L"].rotation_euler', index=0)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Leg_IKFK.L"]["IK / FK"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Leg_IKFK.L"]["Show FK controls"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Leg_IKFK.L"]["Show IK controls"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_floatPivot"].location', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_floatPivot"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.R"].location', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.R"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.R"]["Auto Stretch"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.R"]["Foot Rock"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.R"]["Lengthen Calf"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.R"]["Lengthen Thigh"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.R"]["Twist At Ball"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.R"]["Twist At Heel"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Foot.R"]["Twist At Toe"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Foot.R"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Toe.R"].rotation_euler', index=0)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Heel.R"].rotation_euler', index=0)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_Toe.R"].rotation_euler', index=0)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Leg_IKFK.R"]["IK / FK"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Leg_IKFK.R"]["Show FK controls"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Leg_IKFK.R"]["Show IK controls"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Calf.L"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Calf.R"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Calf.L"]["Lengthen"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Calf.R"]["Lengthen"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_kneePole.L"].location', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_kneePole.L"]["Knee Pin"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_kneePole.R"].location', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_IK_kneePole.R"]["Knee Pin"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Thigh.L"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Thigh.L"]["Lengthen"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Thigh.L"]["Lock Rotation"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_legPin.L"].location', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Thigh.R"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Thigh.R"]["Lengthen"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_FK_Thigh.R"]["Lock Rotation"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_legPin.R"].location', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_COG"].location', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_COG"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Hips"].location', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Hips"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Rim"].location', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_stretchTo"].location', index=2)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Tail_Base"].location', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Tail_Base"]["Lock Rotation"]', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Tail_01"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Tail_02"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Tail_03"].rotation_euler', index=-1)
ksp = ks.paths.add(id_0, 'pose.bones["Ctrl_Tail_04"].rotation_euler', index=-1)

